### ISSUE TITLE
请问 development pods 有什么办法处理呢

### ISSUE THREAD

**Issue by zangtian2** [Amberler/cocoapods-bin#1]
看 cocoapods-imy-bin 对这块不支持，怎么调整可以忽略或规避development pods  出现[!] No podspec found for ‘xxx’ 的问题呢

**Comment by Amberler** [comment]
最好贴下终端的日志看看，是哪一步出现的。
是在打包二进制的时候？还是在上传源码和二进制的podspec的时候？

**Comment by zangtian2** [comment]
代码不太方便贴。但问题是出在打包二进制Generating 的时候。报错
[!] No podspec found for ‘xxx' 
排查后就看到这个依赖是Pods/Development Pods下的
依赖方式是:path => 本地依赖

**Comment by Amberler** [comment]
如果这个 ‘xxx' 是一个在本地的组件，而且是已经开发完成的，建议你上传到自己搭建的git或者其他的私有仓库里面，不然在打包二进制的时候，有依赖这个组件的都不会打包成功的。
美柚的打包二进制，他只依赖自己设置的2个源(源码和二进制)和cocoapods自带的仓库，因此，你必须将你的本地组件podspec传到源码仓库
如果你用的是我的，你可以自己任意自建一个私有源，将‘xxx'上传到私有源，在podfile 里面 添加source即可，或者在other_code_repo_url 添加也行。

**Comment by zangtian2** [comment]
好的，明白了，美柚的小问题不少。。我这里用你的试试。。谢谢老哥
